# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-16 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FEATUREFLAG_CLIENT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('everyone', models.NullBooleanField(help_text=b'Flip this flag on (Yes) or off (No) for everyone, overriding all other settings. Leave as Unknown to use normally.')),
                ('note', models.TextField(blank=True, help_text=b'Note where this Flag is used.')),
                ('client', models.ManyToManyField(blank=True, help_text=b'Activate this flag for these sites.', to=settings.FEATUREFLAG_CLIENT_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=False, help_text=b'Is this flag active?')),
                ('note', models.TextField(blank=True, help_text=b'Note where this Switch is used.')),
            ],
            options={
                'verbose_name_plural': 'Switches',
            },
        ),
    ]
