# Generated by Django 4.0.3 on 2022-03-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featureflag', '0002_auto_2020042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientflag',
            name='everyone',
            field=models.BooleanField(blank=True, help_text='Flip this flag on (Yes) or off (No) for everyone, overriding all other settings. Leave as Unknown to use normally.', null=True),
        ),
    ]
